### ISSUE TITLE
software outdated error when trying to update software

### ISSUE THREAD

**Issue by davalb** [mutecomm/mute#3] opened 2015-11-03 10:34 UTC
When I enter `mutectrl upkeep update` I get 
```
mutectrl: error: ctrlengine: software is outdated, you have to update with `mutectrl upkeep update`
```
So there is no way right now to update the software.

**Comment by frankbraun** [comment] 2015-11-18 14:30
The problem is fixed now. Since the bug was in the update mechanism itself, you have to update Mute manually once to get rid of the problem: cd to `$GOPATH/src/github.com/mutecomm/mute` and execute `git pull` followed by `make`.

Alternatively, just remove the source directory and install from scratch.

Thanks for the report!

**Closed** 2015-11-18 14:30 UTC
